version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: lifequest-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  backend:
    build: ./backend
    container_name: lifequest-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: lifequest-frontend
    restart: always
    ports:
      - "8080:80"   # раньше было 80:80
    depends_on:
      - backend
volumes:
  mongo-data:
