version: "3.9"
services:
  backend:
    build: ./backend
    container_name: lifequest-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    networks:
      - lifequest_net

  frontend:
    build: ./frontend
    container_name: lifequest-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - lifequest_net

networks:
  lifequest_net:
    driver: bridge
